name: "Docker context vps"
description: "Set up docker context for VPS"
runs:
  using: "composite"
  steps:
    - name: fix docker compose with context setup
      run: pip install docker-compose
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat >>~/.ssh/config <<END
        Host server
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.VPS_SSH_USER }}
        SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        SSH_HOST: ${{ secrets.VPS_SSH_HOST }}
    - name: Docker context create and use
      run: |
        docker context create server --docker host=ssh://server
        docker context use server
        docker context ls
