name: "Docker context vps"
description: "Set up docker context for VPS"
inputs:
  ssh_user: 
    description:  'ssh user'
    required: true
  ssh_key: 
    description:  'ssh key'
    required: true
  ssh_host: 
    description:  'ssh host'
    required: true
runs:
  using: "composite"
  steps:
    - name: fix docker compose with context setup
      shell: bash
      run: pip install docker-compose
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.ssh_key }} " > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat >>~/.ssh/config <<END
        Host server
          HostName ${{ inputs.ssh_host }} 
          User ${{ inputs.ssh_user }} 
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
        END
    - name: Docker context create and use
      shell: bash
      run: |
        docker context create server --docker host=ssh://server
        docker context use server
        docker context ls
